/*
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2 , the first 10
 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*
* */

const sumOfEvenFibonacciNumbers = (maxNumber) => {
  const fibonacciTerms = [];

  let nextNumber = 1;

  while(nextNumber < maxNumber) {
    if (fibonacciTerms.length < 3) {
      fibonacciTerms.push(nextNumber);
      nextNumber += 1;
    } else {
      nextNumber = fibonacciTerms[fibonacciTerms.length - 1] + fibonacciTerms[fibonacciTerms.length - 2];
      fibonacciTerms.push(nextNumber);
    }
  }

  const onlyEvenNumbers = fibonacciTerms.filter(number => number % 2 === 0);
  const sumOfEvenNumbers = onlyEvenNumbers.reduce((acc, currentValue) => acc + currentValue, 0)

  return sumOfEvenNumbers;
}

sumOfEvenFibonacciNumbers(4000000); //4613732
